// Code generated by hertz generator.

package follow

import (
	"context"

	"west2/biz/model/base"
	follow "west2/biz/model/follow"
	"west2/database"
	"west2/pkg/middleware"
	"west2/pkg/model"
	"west2/pkg/repository"
	"west2/pkg/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FollowAction .
// @router /relation/action [POST]
func FollowAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req follow.FollowActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	uid := middleware.GetUserFromContext(ctx, c)

	fr := service.NewFollowService(repository.NewFollowRepostory(database.GetMysqlDB()), repository.NewUserRepository(database.GetMysqlDB()))
	err = fr.FollowAction(&model.Follow{
		FollowingId: req.ToUserId,
		FollowerId:  uid,
		Status:      req.ActionType,
	})
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &follow.FollowActionResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "internal server error",
			},
		})
		return
	}
	c.JSON(consts.StatusOK, &follow.FollowActionResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
	})
}

// FollowerList .
// @router /following/list [GET]
func FollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req follow.FollowerListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	fr := service.NewFollowService(repository.NewFollowRepostory(database.GetMysqlDB()), repository.NewUserRepository(database.GetMysqlDB()))

	users, total, err := fr.GetFollowingList(req.UserId, req.PageNum, req.PageSize)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &follow.FollowerListResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "internal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &follow.FollowerListResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Data: &follow.UserList{
			Items: model.UsersToFollowUsers(users),
			Total: total,
		},
	})
}

// FollowedList .
// @router /follower/list [GET]
func FollowedList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req follow.FollowerListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	fr := service.NewFollowService(repository.NewFollowRepostory(database.GetMysqlDB()), repository.NewUserRepository(database.GetMysqlDB()))

	users, total, err := fr.GetFollowerList(req.UserId, req.PageNum, req.PageSize)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &follow.FollowedListResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "internal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &follow.FollowedListResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Data: &follow.UserList{
			Items: model.UsersToFollowUsers(users),
			Total: total,
		},
	})
}

// FriendList .
// @router /friends/list [GET]
func FriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req follow.FriendListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	uid := middleware.GetUserFromContext(ctx, c)
	fr := service.NewFollowService(repository.NewFollowRepostory(database.GetMysqlDB()), repository.NewUserRepository(database.GetMysqlDB()))

	users, total, err := fr.GetFollowerList(uid, req.PageNum, req.PageSize)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &follow.FriendListResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "internal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &follow.FriendListResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Data: &follow.UserList{
			Items: model.UsersToFollowUsers(users),
			Total: total,
		},
	})
}
