// Code generated by hertz generator.

package follow

import (
	"context"
	"west2/biz/model/base"
	"west2/biz/model/user"
	"west2/pkg/middleware"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followedlistMw() []app.HandlerFunc {
	// your code...
	jwtMiddleware, err := middleware.GetJWTMiddleware()
	if err != nil {
		return []app.HandlerFunc{
			func(ctx context.Context, c *app.RequestContext) {
				c.JSON(consts.StatusInternalServerError, &user.UploadAvatarResponse{
					Base: &base.Base{
						Code: consts.StatusInternalServerError,
						Msg:  "internal server error",
					},
				})
				c.Abort() // 中止后续处理
			},
		}

	}

	return []app.HandlerFunc{
		jwtMiddleware.MiddlewareFunc(),
	}
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerlistMw() []app.HandlerFunc {
	// your code...
	jwtMiddleware, err := middleware.GetJWTMiddleware()
	if err != nil {
		return []app.HandlerFunc{
			func(ctx context.Context, c *app.RequestContext) {
				c.JSON(consts.StatusInternalServerError, &user.UploadAvatarResponse{
					Base: &base.Base{
						Code: consts.StatusInternalServerError,
						Msg:  "internal server error",
					},
				})
				c.Abort() // 中止后续处理
			},
		}

	}

	return []app.HandlerFunc{
		jwtMiddleware.MiddlewareFunc(),
	}
}

func _friendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendlistMw() []app.HandlerFunc {
	// your code...
	jwtMiddleware, err := middleware.GetJWTMiddleware()
	if err != nil {
		return []app.HandlerFunc{
			func(ctx context.Context, c *app.RequestContext) {
				c.JSON(consts.StatusInternalServerError, &user.UploadAvatarResponse{
					Base: &base.Base{
						Code: consts.StatusInternalServerError,
						Msg:  "internal server error",
					},
				})
				c.Abort() // 中止后续处理
			},
		}

	}

	return []app.HandlerFunc{
		jwtMiddleware.MiddlewareFunc(),
	}
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followactionMw() []app.HandlerFunc {
	// your code...
	jwtMiddleware, err := middleware.GetJWTMiddleware()
	if err != nil {
		return []app.HandlerFunc{
			func(ctx context.Context, c *app.RequestContext) {
				c.JSON(consts.StatusInternalServerError, &user.UploadAvatarResponse{
					Base: &base.Base{
						Code: consts.StatusInternalServerError,
						Msg:  "internal server error",
					},
				})
				c.Abort() // 中止后续处理
			},
		}

	}

	return []app.HandlerFunc{
		jwtMiddleware.MiddlewareFunc(),
	}
}
