// Code generated by hertz generator.

package comment

import (
	"context"

	"west2/biz/model/base"
	comment "west2/biz/model/comment"
	"west2/database"
	"west2/pkg/middleware"
	"west2/pkg/model"
	"west2/pkg/repository"
	"west2/pkg/service"
	"west2/util"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CommentPublish .
// @router /comment/publish [POST]
func CommentPublish(ctx context.Context, c *app.RequestContext) {
	var err error
	var req comment.CommentPublishRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	cs := service.NewCommentService(repository.NewCommentRepository(database.GetMysqlDB()))
	err = cs.Publish(&model.Comment{
		Id:       util.GetID(),
		VideoId:  req.VideoId,
		Uid:      middleware.GetUserFromContext(ctx, c),
		ParentId: req.CommentId,
		Content:  req.Content,
	})
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &comment.CommentPublishResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "internal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusCreated, &comment.CommentPublishResponse{
		Base: &base.Base{
			Code: consts.StatusCreated,
			Msg:  "success",
		},
	})
}

// CommentList .
// @router /comment/list [GET]
func CommentList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req comment.CommentListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	cs := service.NewCommentService(repository.NewCommentRepository(database.GetMysqlDB()))
	comments, err := cs.GetCommentList(req.VideoId, req.CommentId, req.PageNum, req.PageSize)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &comment.CommentListResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "internal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &comment.CommentListResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Data: &comment.CommentList{
			Items: model.CommentsToResComments(comments),
		},
	})
}

// Delete .
// @router /comment/delete [DELETE]
func Delete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req comment.DeleteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	cs := service.NewCommentService(repository.NewCommentRepository(database.GetMysqlDB()))
	if req.CommentId != "" {
		err = cs.DeleteById(req.CommentId)
	} else {
		err = cs.DeleteByVideoId(req.VideoId)
	}

	if err != nil {
		c.JSON(consts.StatusInternalServerError, &comment.DeleteResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "internal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusNoContent, &comment.DeleteResponse{
		Base: &base.Base{
			Code: consts.StatusNoContent,
			Msg:  "success",
		},
	})
}
