// Code generated by hertz generator.

package chat

import (
	"context"
	"log"
	"west2/pkg/middleware"
	"west2/pkg/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/websocket"
)

// Chat .
// @router /chat [GET]
func Chat(ctx context.Context, c *app.RequestContext) {
	var upgrader = websocket.HertzUpgrader{}
	cs := service.NewChatService()
	err := upgrader.Upgrade(c, func(conn *websocket.Conn) {
		uid := middleware.GetUserFromContext(ctx, c)
		if uid == "" {
			c.AbortWithStatus(400)
			return
		}
		for {
			mt, message, err := conn.ReadMessage()
			if err != nil {
				log.Println("read:", err)
				break
			}
			message, err = cs.Chat(uid, message)
			if err != nil {
				c.AbortWithStatus(400)
				return
			}
			err = conn.WriteMessage(mt, message)
			if err != nil {
				c.AbortWithStatus(400)
				return
			}
		}
	})
	if err != nil {
		log.Print("upgrade:", err)
		c.AbortWithStatus(400)
		return
	}
}
