// Code generated by hertz generator.

package video

import (
	"context"

	"west2/biz/model/base"
	video "west2/biz/model/video"
	"west2/database"
	"west2/pkg/middleware"
	"west2/pkg/model"
	"west2/pkg/repository"
	"west2/pkg/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// VideoStream .
// @router /video/feed [GET]
func VideoStream(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoStreamRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	vs := service.NewVideoService(repository.NewVideoRepository(database.GetMysqlDB()), repository.NewUserRepository(database.GetMysqlDB()))
	videos, err := vs.GetVideoStream(req.LatestTime)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &video.VideoStreamResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "inernal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &video.VideoStreamResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Data: &video.VideoList{
			Items: model.VideosToResVideos(videos),
		},
	})
}

// Publish .
// @router /video/publish [POST]
func Publish(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	uid := middleware.GetUserFromContext(ctx, c)

	vs := service.NewVideoService(repository.NewVideoRepository(database.GetMysqlDB()), repository.NewUserRepository(database.GetMysqlDB()))
	err = vs.Publish(req.Title, req.Description, req.Data, uid)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &video.PublishResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "inernal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &video.PublishResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
	})
}

// PublishList .
// @router /video/list [GET]
func PublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	vs := service.NewVideoService(repository.NewVideoRepository(database.GetMysqlDB()), repository.NewUserRepository(database.GetMysqlDB()))
	videos, total, err := vs.GetVideosByUid(req.Uid, req.PageNum, req.PageSize)

	if err != nil {
		c.JSON(consts.StatusInternalServerError, &video.PublishListResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "inernal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &video.PublishListResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Data: &video.VideoList{
			Items: model.VideosToResVideos(videos),
			Total: &total,
		},
	})
}

// Popular .
// @router /video/popular [GET]
func Popular(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PopularRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	vs := service.NewVideoService(repository.NewVideoRepository(database.GetMysqlDB()), repository.NewUserRepository(database.GetMysqlDB()))
	videos, err := vs.GetVideosByVisitCount(req.PageNum, req.PageSize)

	if err != nil {
		c.JSON(consts.StatusInternalServerError, &video.PopularResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "inernal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &video.PopularResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Data: &video.VideoList{
			Items: model.VideosToResVideos(videos),
		},
	})
}

// Search .
// @router /video/search [POST]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.SearchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	vs := service.NewVideoService(repository.NewVideoRepository(database.GetMysqlDB()), repository.NewUserRepository(database.GetMysqlDB()))
	videos, total, err := vs.Search(req.Keywords, req.FromDate, req.ToDate, req.Username, req.PageNum, req.PageSize)

	if err != nil {
		c.JSON(consts.StatusInternalServerError, &video.SearchResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "inernal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &video.SearchResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Data: &video.VideoList{
			Items: model.VideosToResVideos(videos),
			Total: &total,
		},
	})
}
