// Code generated by hertz generator.

package video

import (
	"context"

	"west2/biz/model/base"
	video "west2/biz/model/video"
	"west2/database"
	"west2/pkg/middleware"
	"west2/pkg/model"
	"west2/pkg/repository"
	"west2/pkg/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var dateFormat string = "2006-01-02T15:04:05.000Z"

func videoToResVideo(v *model.Video) *video.Video {
	visitCount := v.VisitCount
	likeCount := v.LikeCount
	commentCount := v.CommentCount
	return &video.Video{
		Id:           v.Id,
		Uid:          v.Uid,
		VideoUrl:     v.VideoUrl,
		CoverUrl:     v.CoverUrl,
		Title:        v.Title,
		Description:  v.Description,
		VisitCount:   &visitCount,
		LikeCount:    &likeCount,
		CommentCount: &commentCount,
		CreatedAt:    v.CreatedAt.Format(dateFormat),
		UpdatedAt:    v.UpdatedAt.Format(dateFormat),
		DeletedAt:    v.DeletedAt.Format(dateFormat),
	}
}

func videosToResVideos(videos []*model.Video) []*video.Video {
	var videosRes []*video.Video
	for _, v := range videos {
		videosRes = append(videosRes, videoToResVideo(v))
	}
	return videosRes
}

// VideoStream .
// @router /video/feed [GET]
func VideoStream(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoStreamRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	vs := service.NewVideoService(repository.NewVideoRepository(database.GetMysqlDB()))
	videos, err := vs.GetVideoStream(req.LatestTime)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &video.VideoStreamResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "inernal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &video.VideoStreamResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Data: &video.VideoList{
			Items: videosToResVideos(videos),
		},
	})
}

// Publish .
// @router /video/publish [POST]
func Publish(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	uid := middleware.GetUserFromContext(ctx, c)

	vs := service.NewVideoService(repository.NewVideoRepository(database.GetMysqlDB()))
	err = vs.Publish(req.Title, req.Description, req.Data, uid)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &video.PublishResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "inernal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &video.PublishResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
	})
}

// PublishList .
// @router /video/list [GET]
func PublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.PublishListResponse)

	c.JSON(consts.StatusOK, resp)
}

// Popular .
// @router /video/popular [GET]
func Popular(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PopularRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.PopularResponse)

	c.JSON(consts.StatusOK, resp)
}

// Search .
// @router /video/search [POST]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.SearchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.SearchResponse)

	c.JSON(consts.StatusOK, resp)
}
