// Code generated by hertz generator.

package like

import (
	"context"

	"west2/biz/model/base"
	like "west2/biz/model/like"
	"west2/biz/model/video"
	"west2/database"
	"west2/pkg/middleware"
	"west2/pkg/model"
	"west2/pkg/repository"
	"west2/pkg/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// LikeAction .
// @router /like/action [POST]
func LikeAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req like.LikeActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	ls := service.NewLikeService(repository.NewLikeReposirty(database.GetMysqlDB()), repository.NewVideoRepository(database.GetMysqlDB()))
	err = ls.LikeAction(&model.Like{
		CommentId: req.CommentId,
		VideoId:   req.VideoId,
		Uid:       middleware.GetUserFromContext(ctx, c),
		Status:    req.ActionType,
	})
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &like.LikeActionResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "internal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &like.LikeActionResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
	})
}

// LikeList .
// @router /like/list [GET]
func LikeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req like.LikeListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	ls := service.NewLikeService(repository.NewLikeReposirty(database.GetMysqlDB()), repository.NewVideoRepository(database.GetMysqlDB()))
	videos, err := ls.GetVideoListByLike(req.Uid, req.PageNum, req.PageSize)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &like.LikeListResponse{
			Base: &base.Base{
				Code: consts.StatusInternalServerError,
				Msg:  "internal server error",
			},
		})
		return
	}

	c.JSON(consts.StatusOK, &like.LikeListResponse{
		Base: &base.Base{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Data: &video.VideoList{
			Items: model.VideosToResVideos(videos),
		},
	})
}
