// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	chat "west2/biz/router/chat"
	comment "west2/biz/router/comment"
	follow "west2/biz/router/follow"
	like "west2/biz/router/like"
	user "west2/biz/router/user"
	video "west2/biz/router/video"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	chat.Register(r)

	follow.Register(r)

	comment.Register(r)

	like.Register(r)

	video.Register(r)

	user.Register(r)

}
